### ISSUE TITLE
Building error : `open_spiel/abseil-cpp/absl/container/internal/container_memory.h:66:27: error: unknown type name 'uintptr_t'; did you mean '__intptr_t'?`

### ISSUE THREAD

**Issue by Gardene-el** [google-deepmind/open_spiel#1334]
I've met an error on building, here is the log:

```
Cr0c0diLe<Lieutenaunt>*open_spiel*>./open_spiel/scripts/build_and_run_tests.sh
Running ./open_spiel/scripts/build_and_run_tests.sh from /home/Cr0c0diLe/Documents/repo-python/open_spiel
Reusing virtualenv from ./venv.
Skipping installation of requirements.txt.
Building and testing in /home/Cr0c0diLe/Documents/repo-python/open_spiel/build using 'python' (version 3.13.3).
-- The C compiler identification is GNU 15.1.1
-- The CXX compiler identification is Clang 19.1.7
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Current build type is: Testing
OPEN_SPIEL_BUILD_WITH_ACPC: OFF 
OPEN_SPIEL_BUILD_WITH_HANABI: OFF 
OPEN_SPIEL_BUILD_WITH_JULIA: OFF 
OPEN_SPIEL_BUILD_WITH_LIBNOP: OFF 
OPEN_SPIEL_BUILD_WITH_LIBTORCH: OFF 
OPEN_SPIEL_BUILD_WITH_PYTHON: ON 
OPEN_SPIEL_BUILD_WITH_XINXIN: OFF 
OPEN_SPIEL_BUILD_WITH_ROSHAMBO: OFF 
OPEN_SPIEL_BUILD_WITH_GAMUT: OFF 
OPEN_SPIEL_BUILD_WITH_ORTOOLS: OFF 
OPEN_SPIEL_ENABLE_JAX: AUTO 
OPEN_SPIEL_ENABLE_PYTORCH: AUTO 
OPEN_SPIEL_ENABLE_PYTHON_MISC: OFF 
OPEN_SPIEL_BUILDING_WHEEL not set. Defaults to OFF
OPEN_SPIEL_BUILDING_WHEEL: OFF 
-- Performing Test ABSL_INTERNAL_AT_LEAST_CXX17
-- Performing Test ABSL_INTERNAL_AT_LEAST_CXX17 - Success
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
Not building wheel. Finding Python normally...
-- Found Python3: /home/Cr0c0diLe/Documents/repo-python/open_spiel/venv/bin/python3.13 (found version "3.13.3") found components: Interpreter Development Development.Module Development.Embed
Python executable: /home/Cr0c0diLe/Documents/repo-python/open_spiel/venv/bin/python3.13
Python include dirs: /usr/include/python3.13
Python library dirs: /usr/lib
OPEN_SPIEL_ENABLE_JAX set to AUTO. Detecting Jax...
Not found. Enable printing errors in python/CMakeLists.txt to see output.
OPEN_SPIEL_ENABLE_PYTORCH set to AUTO. Detecting PyTorch...
Not found. Enable printing errors in python/CMakeLists.txt to see output.
-- Configuring done (0.7s)
-- Generating done (1.2s)
-- Build files have been written to: /home/Cr0c0diLe/Documents/repo-python/open_spiel/build
Building project
[  0%] Building CXX object abseil-cpp/absl/debugging/CMakeFiles/absl_leak_check.dir/leak_check.cc.o
[  0%] Building CXX object abseil-cpp/absl/log/CMakeFiles/absl_log_internal_nullguard.dir/internal/nullguard.cc.o
[  0%] Building CXX object CMakeFiles/open_spiel_core.dir/canonical_game_strings.cc.o
[  0%] Building CXX object abseil-cpp/absl/flags/CMakeFiles/absl_flags_commandlineflag_internal.dir/internal/commandlineflag.cc.o
[  0%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_log_severity.dir/log_severity.cc.o
[  0%] Building CXX object CMakeFiles/open_spiel_core.dir/matrix_game.cc.o
[  0%] Building CXX object CMakeFiles/open_spiel_core.dir/observer.cc.o
[  0%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_civil_time.dir/internal/cctz/src/civil_time_detail.cc.o
[  0%] Building CXX object abseil-cpp/absl/random/CMakeFiles/absl_random_internal_platform.dir/internal/randen_round_keys.cc.o
[  0%] Building CXX object abseil-cpp/absl/numeric/CMakeFiles/absl_int128.dir/int128.cc.o
[  0%] Building CXX object CMakeFiles/open_spiel_core.dir/spiel_bots.cc.o
[  1%] Building CXX object CMakeFiles/open_spiel_core.dir/game_parameters.cc.o
[  1%] Building CXX object CMakeFiles/open_spiel_core.dir/action_view.cc.o
[  1%] Building CXX object CMakeFiles/open_spiel_core.dir/spiel.cc.o
[  1%] Building CXX object abseil-cpp/absl/profiling/CMakeFiles/absl_exponential_biased.dir/internal/exponential_biased.cc.o
[  1%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_spinlock_wait.dir/internal/spinlock_wait.cc.o
[  1%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time_zone.dir/internal/cctz/src/time_zone_format.cc.o
[  1%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_strerror.dir/internal/strerror.cc.o
[  2%] Building CXX object CMakeFiles/open_spiel_core.dir/spiel_utils.cc.o
[  2%] Building CXX object CMakeFiles/open_spiel_core.dir/tensor_game.cc.o
[  2%] Building CXX object CMakeFiles/open_spiel_core.dir/policy.cc.o
[  2%] Building CXX object CMakeFiles/open_spiel_core.dir/utils/usage_logging.cc.o
[  2%] Building CXX object CMakeFiles/open_spiel_core.dir/simultaneous_move_game.cc.o
[  2%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time_zone.dir/internal/cctz/src/time_zone_libc.cc.o
[  3%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time_zone.dir/internal/cctz/src/time_zone_fixed.cc.o
[  3%] Building CXX object abseil-cpp/absl/random/CMakeFiles/absl_random_seed_gen_exception.dir/seed_gen_exception.cc.o
[  3%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time_zone.dir/internal/cctz/src/time_zone_if.cc.o
[  3%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time_zone.dir/internal/cctz/src/time_zone_impl.cc.o
[  3%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time_zone.dir/internal/cctz/src/time_zone_info.cc.o
[  3%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time_zone.dir/internal/cctz/src/time_zone_lookup.cc.o
[  3%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time_zone.dir/internal/cctz/src/time_zone_posix.cc.o
[  4%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time_zone.dir/internal/cctz/src/zone_info_source.cc.o
[  4%] Linking CXX static library libabsl_leak_check.a
[  4%] Linking CXX static library libabsl_flags_commandlineflag_internal.a
[  4%] Linking CXX static library libabsl_random_internal_platform.a
[  4%] Linking CXX static library libabsl_log_internal_nullguard.a
[  4%] Built target absl_flags_commandlineflag_internal
[  4%] Built target absl_leak_check
[  5%] Linking CXX static library libabsl_spinlock_wait.a
[  5%] Built target absl_random_internal_platform
[  5%] Building CXX object abseil-cpp/absl/random/CMakeFiles/absl_random_internal_randen_hwaes_impl.dir/internal/randen_hwaes.cc.o
[  5%] Building CXX object abseil-cpp/absl/random/CMakeFiles/absl_random_internal_randen_slow.dir/internal/randen_slow.cc.o
[  5%] Built target absl_log_internal_nullguard
[  5%] Built target absl_spinlock_wait
In file included from /home/Cr0c0diLe/Documents/repo-python/open_spiel/open_spiel/observer.cc:15:
In file included from /home/Cr0c0diLe/Documents/repo-python/open_spiel/open_spiel/../open_spiel/observer.h:50:
In file included from /home/Cr0c0diLe/Documents/repo-python/open_spiel/open_spiel/../open_spiel/abseil-cpp/absl/container/flat_hash_set.h:37:
/home/Cr0c0diLe/Documents/repo-python/open_spiel/open_spiel/abseil-cpp/absl/container/internal/container_memory.h:66:27: error: unknown type name 'uintptr_t'; did you mean '__intptr_t'?
   66 |   assert(reinterpret_cast<uintptr_t>(p) % Alignment == 0 &&
      |                           ^~~~~~~~~
      |                           __intptr_t
/usr/include/assert.h:100:27: note: expanded from macro 'assert'
  100 |      (static_cast <bool> (expr)                                         \
      |                           ^
/usr/include/bits/types.h:207:25: note: '__intptr_t' declared here
  207 | __STD_TYPE __SWORD_TYPE __intptr_t;
      |                         ^
[  6%] Linking CXX static library libabsl_strerror.a
[  6%] Linking CXX static library libabsl_exponential_biased.a
[  6%] Linking CXX static library libabsl_log_severity.a
[  6%] Built target absl_strerror
[  6%] Built target absl_exponential_biased
[  6%] Building CXX object abseil-cpp/absl/profiling/CMakeFiles/absl_periodic_sampler.dir/internal/periodic_sampler.cc.o
[  6%] Linking CXX static library libabsl_random_seed_gen_exception.a
[  6%] Built target absl_log_severity
[  6%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_raw_logging_internal.dir/internal/raw_logging.cc.o
[  6%] Built target absl_random_seed_gen_exception
[  7%] Linking CXX static library libabsl_random_internal_randen_hwaes_impl.a
[  7%] Built target absl_random_internal_randen_hwaes_impl
[  7%] Linking CXX static library libabsl_periodic_sampler.a
[  7%] Building CXX object abseil-cpp/absl/random/CMakeFiles/absl_random_internal_randen_hwaes.dir/internal/randen_detect.cc.o
[  7%] Built target absl_periodic_sampler
[  7%] Linking CXX static library libabsl_random_internal_randen_hwaes.a
[  7%] Linking CXX static library libabsl_int128.a
[  7%] Built target absl_random_internal_randen_hwaes
[  7%] Linking CXX static library libabsl_civil_time.a
[  7%] Built target absl_int128
[  7%] Linking CXX static library libabsl_random_internal_randen_slow.a
[  7%] Built target absl_civil_time
[  7%] Built target absl_random_internal_randen_slow
[  7%] Building CXX object abseil-cpp/absl/random/CMakeFiles/absl_random_internal_randen.dir/internal/randen.cc.o
[  7%] Linking CXX static library libabsl_raw_logging_internal.a
[  7%] Linking CXX static library libabsl_random_internal_randen.a
[  7%] Built target absl_raw_logging_internal
[  7%] Built target absl_random_internal_randen
[  8%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_throw_delegate.dir/internal/throw_delegate.cc.o
[  8%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_base.dir/internal/thread_identity.cc.o
[  8%] Building CXX object abseil-cpp/absl/types/CMakeFiles/absl_bad_optional_access.dir/bad_optional_access.cc.o
[  8%] Building CXX object abseil-cpp/absl/debugging/CMakeFiles/absl_debugging_internal.dir/internal/vdso_support.cc.o
[  8%] Building CXX object abseil-cpp/absl/types/CMakeFiles/absl_bad_variant_access.dir/bad_variant_access.cc.o
[  8%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_base.dir/internal/cycleclock.cc.o
[  8%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_base.dir/internal/unscaledcycleclock.cc.o
[  8%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_scoped_set_env.dir/internal/scoped_set_env.cc.o
[  8%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_base.dir/internal/spinlock.cc.o
[  8%] Building CXX object abseil-cpp/absl/debugging/CMakeFiles/absl_debugging_internal.dir/internal/elf_mem_image.cc.o
[  8%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_base.dir/internal/sysinfo.cc.o
[  8%] Building CXX object abseil-cpp/absl/debugging/CMakeFiles/absl_debugging_internal.dir/internal/address_is_readable.cc.o
[  8%] Building CXX object abseil-cpp/absl/types/CMakeFiles/absl_bad_any_cast_impl.dir/bad_any_cast.cc.o
[  8%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_cordz_functions.dir/internal/cordz_functions.cc.o
[  8%] Linking CXX static library libabsl_bad_any_cast_impl.a
1 error generated.
make[2]: *** [CMakeFiles/open_spiel_core.dir/build.make:135: CMakeFiles/open_spiel_core.dir/observer.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  8%] Built target absl_bad_any_cast_impl
[  8%] Linking CXX static library libabsl_bad_optional_access.a
[  9%] Linking CXX static library libabsl_bad_variant_access.a
[  9%] Linking CXX static library libabsl_debugging_internal.a
[  9%] Built target absl_bad_optional_access
[  9%] Built target absl_bad_variant_access
[  9%] Linking CXX static library libabsl_scoped_set_env.a
[  9%] Built target absl_debugging_internal
[  9%] Building CXX object abseil-cpp/absl/debugging/CMakeFiles/absl_stacktrace.dir/stacktrace.cc.o
[  9%] Built target absl_scoped_set_env
[  9%] Linking CXX static library libabsl_stacktrace.a
[  9%] Linking CXX static library libabsl_throw_delegate.a
[  9%] Built target absl_stacktrace
[  9%] Built target absl_throw_delegate
[ 10%] Linking CXX static library libabsl_cordz_functions.a
[ 10%] Built target absl_cordz_functions
[ 10%] Linking CXX static library libabsl_base.a
[ 10%] Linking CXX static library libabsl_time_zone.a
[ 10%] Built target absl_base
[ 10%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_strings_internal.dir/internal/escaping.cc.o
[ 11%] Building CXX object abseil-cpp/absl/log/CMakeFiles/absl_log_internal_conditions.dir/internal/conditions.cc.o
[ 11%] Building CXX object abseil-cpp/absl/hash/CMakeFiles/absl_city.dir/internal/city.cc.o
[ 11%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_strings_internal.dir/internal/ostringstream.cc.o
[ 11%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_strings_internal.dir/internal/utf8.cc.o
[ 11%] Building CXX object abseil-cpp/absl/hash/CMakeFiles/absl_low_level_hash.dir/internal/low_level_hash.cc.o
[ 12%] Building CXX object abseil-cpp/absl/debugging/CMakeFiles/absl_demangle_internal.dir/internal/demangle.cc.o
[ 12%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_malloc_internal.dir/internal/low_level_alloc.cc.o
[ 12%] Building CXX object abseil-cpp/absl/crc/CMakeFiles/absl_crc_cpu_detect.dir/internal/cpu_detect.cc.o
[ 12%] Built target absl_time_zone
[ 12%] Linking CXX static library libabsl_log_internal_conditions.a
[ 12%] Built target absl_log_internal_conditions
[ 12%] Linking CXX static library libabsl_low_level_hash.a
[ 12%] Built target absl_low_level_hash
[ 13%] Linking CXX static library libabsl_city.a
[ 13%] Built target absl_city
[ 13%] Linking CXX static library libabsl_crc_cpu_detect.a
[ 13%] Linking CXX static library libabsl_strings_internal.a
[ 13%] Built target absl_crc_cpu_detect
[ 14%] Building CXX object abseil-cpp/absl/crc/CMakeFiles/absl_crc_internal.dir/internal/crc.cc.o
[ 14%] Building CXX object abseil-cpp/absl/crc/CMakeFiles/absl_crc_internal.dir/internal/crc_x86_arm_combined.cc.o
[ 14%] Built target absl_strings_internal
[ 14%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_strings.dir/str_split.cc.o
[ 14%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_strings.dir/ascii.cc.o
[ 14%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_strings.dir/internal/charconv_bigint.cc.o
[ 14%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_strings.dir/escaping.cc.o
[ 14%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_strings.dir/charconv.cc.o
[ 14%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_strings.dir/internal/charconv_parse.cc.o
[ 15%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_strings.dir/internal/stringify_sink.cc.o
[ 15%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_strings.dir/internal/memutil.cc.o
[ 15%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_strings.dir/internal/damerau_levenshtein_distance.cc.o
[ 15%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_strings.dir/match.cc.o
[ 15%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_strings.dir/numbers.cc.o
[ 15%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_strings.dir/str_cat.cc.o
[ 15%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_strings.dir/str_replace.cc.o
[ 15%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_strings.dir/string_view.cc.o
[ 16%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_strings.dir/substitute.cc.o
[ 16%] Linking CXX static library libabsl_demangle_internal.a
[ 16%] Linking CXX static library libabsl_malloc_internal.a
[ 16%] Built target absl_demangle_internal
[ 16%] Built target absl_malloc_internal
[ 16%] Building CXX object abseil-cpp/absl/synchronization/CMakeFiles/absl_graphcycles_internal.dir/internal/graphcycles.cc.o
[ 16%] Linking CXX static library libabsl_graphcycles_internal.a
[ 16%] Linking CXX static library libabsl_crc_internal.a
[ 16%] Built target absl_graphcycles_internal
[ 16%] Built target absl_crc_internal
[ 16%] Linking CXX static library libabsl_strings.a
[ 16%] Built target absl_strings
[ 17%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_str_format_internal.dir/internal/str_format/bind.cc.o
[ 17%] Building CXX object abseil-cpp/absl/random/CMakeFiles/absl_random_distributions.dir/gaussian_distribution.cc.o
[ 17%] Building CXX object abseil-cpp/absl/flags/CMakeFiles/absl_flags_commandlineflag.dir/commandlineflag.cc.o
[ 17%] Building CXX object abseil-cpp/absl/crc/CMakeFiles/absl_crc32c.dir/internal/crc_memcpy_fallback.cc.o
[ 17%] Building CXX object abseil-cpp/absl/crc/CMakeFiles/absl_crc32c.dir/internal/crc_memcpy_x86_64.cc.o
[ 17%] Building CXX object abseil-cpp/absl/random/CMakeFiles/absl_random_internal_seed_material.dir/internal/seed_material.cc.o
[ 17%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_str_format_internal.dir/internal/str_format/float_conversion.cc.o
[ 17%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_str_format_internal.dir/internal/str_format/parser.cc.o
[ 18%] Building CXX object abseil-cpp/absl/random/CMakeFiles/absl_random_distributions.dir/discrete_distribution.cc.o
[ 18%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time.dir/civil_time.cc.o
[ 18%] Building CXX object abseil-cpp/absl/debugging/CMakeFiles/absl_symbolize.dir/symbolize.cc.o
[ 18%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time.dir/duration.cc.o
[ 18%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time.dir/clock.cc.o
[ 18%] Building CXX object abseil-cpp/absl/hash/CMakeFiles/absl_hash.dir/internal/hash.cc.o
[ 19%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_str_format_internal.dir/internal/str_format/arg.cc.o
[ 18%] Building CXX object abseil-cpp/absl/crc/CMakeFiles/absl_crc32c.dir/crc32c.cc.o
[ 19%] Building CXX object abseil-cpp/absl/log/CMakeFiles/absl_log_internal_proto.dir/internal/proto.cc.o
[ 19%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time.dir/format.cc.o
[ 19%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_str_format_internal.dir/internal/str_format/extension.cc.o
[ 19%] Building CXX object abseil-cpp/absl/crc/CMakeFiles/absl_crc32c.dir/internal/crc_non_temporal_memcpy.cc.o
[ 19%] Building CXX object abseil-cpp/absl/time/CMakeFiles/absl_time.dir/time.cc.o
[ 19%] Building CXX object abseil-cpp/absl/strings/CMakeFiles/absl_str_format_internal.dir/internal/str_format/output.cc.o
make[1]: *** [CMakeFiles/Makefile2:1605: CMakeFiles/open_spiel_core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 19%] Linking CXX static library libabsl_hash.a
[ 19%] Linking CXX static library libabsl_random_internal_seed_material.a
[ 19%] Built target absl_hash
[ 19%] Built target absl_random_internal_seed_material
[ 19%] Linking CXX static library libabsl_flags_commandlineflag.a
[ 19%] Linking CXX static library libabsl_crc32c.a
[ 19%] Built target absl_flags_commandlineflag
[ 19%] Built target absl_crc32c
[ 19%] Linking CXX static library libabsl_log_internal_proto.a
[ 19%] Linking CXX static library libabsl_random_distributions.a
[ 19%] Built target absl_log_internal_proto
[ 19%] Built target absl_random_distributions
[ 19%] Linking CXX static library libabsl_time.a
[ 19%] Linking CXX static library libabsl_symbolize.a
[ 19%] Built target absl_time
[ 19%] Built target absl_symbolize
[ 19%] Linking CXX static library libabsl_str_format_internal.a
[ 19%] Built target absl_str_format_internal
make: *** [Makefile:101: all] Error 2
Exiting virtualenv
```

It could be easily fixed by adding `#include<cstdint>`. Yet, I'm not sure what is a good way to report( or pull request) this, since it is a LTS version of other project, or if I've got something wrong.

Here is my environment:
```
Cr0c0diLe<Lieutenaunt>*open_spiel*>cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

Cr0c0diLe<Lieutenaunt>*open_spiel*>clang++ --version
clang version 19.1.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

Cr0c0diLe<Lieutenaunt>*open_spiel*>cmake --version
cmake version 4.0.1-dirty

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by lanctot** [comment]
Nice find, thanks! 

I think this is happening because you're using a very new compiler **and** because we have pegged our version of abseil (see [here](https://github.com/google-deepmind/open_spiel/blob/9d9aa3698671f800b79c2009c23018f263f64562/open_spiel/scripts/install.sh#L141)). 

My guess is that the abseil devs have already fixed this upstream. Could I ask you to try a newer abseil? Remove everything under `open_spiel/abseil-cpp`, then modify the `install.sh` to remove the checkout to a specific commit, rerun `install.sh` and try again? If that works then we should change the commit in install.sh to the most recent one (and I'd be happy if you submitted a PR for this)

**Comment by lanctot** [comment]
Actually it was super easy to try directly from github.

https://github.com/google-deepmind/open_spiel/pull/1335

If it passes tests (sometimes it can break tests there are backward-incompatible changes or deprecated functions that we're still using) then I guess this will fix the issue on your side too.

**Comment by lanctot** [comment]
Ok it breaks a few minor things in specific cases that don't surprise me (but require nontrivial fixes that I have to defer to another time)... 

But the most recent Ubuntu tests pass with this new PR applied. So those minor breakages above almost certaintly won't affect you, so it should work out. Please let me know.

**Comment by Gardene-el** [comment]
That breakages don't affect me, the building succeed without error. Good luck on your pr test.
